# This is a basic workflow to help you get started with Actions

name: Deploy to Ali ECS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    uses: modenicheng/blog/.github/workflows/build.yml@master
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: Artifact for ${{ github.sha }}
          path: ./

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.ECS_HOST }} >> ~/.ssh/known_hosts

      - name: Upload and deploy
        run: |
          echo "Uploading artifact..."
          scp ./dist.tar.gz ${{ secrets.ECS_USER }}@${{ secrets.ECS_HOST }}:/srv/

          echo "Deploying on server..."
          ssh ${{ secrets.ECS_USER }}@${{ secrets.ECS_HOST }} << 'EOF'
            set -e

            echo "Extracting files..."
            cd /srv
            tar -zxvf dist.tar.gz

            mv ./dist/* blog-artifact
            rm -rf ./dist
            rm -f dist.tar.gz

            echo "Restarting Nginx..."
            sudo systemctl restart nginx

            echo "Deployment completed!"
          EOF
